### ISSUE TITLE
Tx read isolation

### ISSUE THREAD

**Issue by brunotm** [xujiajun/nutsdb#20]
Hi @xujiajun,

By looking at the code is not clear that we're getting values of our own pending writes when reading within a transaction. I might be probably missing something.

Thanks.

Example:
https://github.com/xujiajun/nutsdb/blob/5705bf9fa79506cbc5b32bf9cf5a0a4940e84716/tx_bptree.go#L25

**Comment by xujiajun** [comment]
Hi @brunotm ，about isolation ,nutsDB supports serializable transactions, it means when a read-only transaction has started,  other read-write(write only)  transaction will wait till this  read-only transaction  finishes. So you will not get values of the pending writes when reading within a transaction.

**Comment by brunotm** [comment]
Hi @xujiajun,

My point was that within a rw transaction, we should be able to read from its own pending writes.

Not about dirty/phantom reads from other transactions.

**Comment by xujiajun** [comment]
@brunotm, we certainly should be able to read from its own pending writes within a read-write transaction, the reason is the pending writes were yourself supplied. 

For example below, key (name1) and val( val1) its own pending writes data.

```
if err := db.Update(
	func(tx *nutsdb.Tx) error {
		key := []byte("name1") //pending write key
		val := []byte("val1")// pending write value
		return tx.Put(bucket, key, val, 0) set value=val1
	}); err != nil {
	log.Fatal(err)
}
```

If you use `Get` function, it means you wanna a read transaction in the nutsDB.

```
if err := db.Update(
	func(tx *nutsdb.Tx) error {
		key := []byte("name2")
		entry,_ := tx.Get(bucket,[]byte("name1")) // a read transaction
		return tx.Put(bucket, key, entry.Value, 0) // set key ,value
	}); err != nil {
	log.Fatal(err)
}

```

**Comment by brunotm** [comment]
@xujiajun this not a consistent and can break lots of things.

Better than stating (in bold) in the documentation that this is the intended behaviour, would be having 2 different transaction types for both RO and WO transactions. Where read functions are not available in a WO transaction and write functions not available in RO.

However, that would be the same as having no transactions and protecting the db crud ops with a 
simple rwmutex with an added db.PutAll(KeysAndValues ...KV).

thanks.

**Comment by xujiajun** [comment]
Hi ，@brunotm.   
yes, would be having 2 different transaction types for both RO and WO(RW) transactions. 
Actually read functions are available in a WO(RW) / RO transaction, but  write functions not available in RO, they only available in a WO(RW) transaction.

In the NutsDB ，when you use  like `db.Put(KeysAndValues ...KV)` just do some pending write operations（ real operations）,but  their status are uncommitted,   till the last operation is success, now the last operation will be marked committed (others still uncommitted status), and  a tx will true committed, all the write operations data will be indexed, so the  next RO/ RW transaction can read the values. Otherwise it will rollback. Not only just simple mutex with an added db.Put operations.

**Comment by brunotm** [comment]
> In the NutsDB ，when you use like db.Put(KeysAndValues ...KV) just do some pending write operations（ real operations）,but their status are uncommitted, till the last operation is success, now the last operation will be marked committed (others still uncommitted status), and a tx will true committed, all the write operations data will be indexed, so the next RO/ RW transaction can read the values. Otherwise it will rollback. Not only just simple mutex with an added db.Put operations.

Sure. I was oversimplifying for the sake of the example.

Thanks for the good work on nutsdb, looks very promising!
